CraZySacX/node-jdbc

README.md
lib/jdbc.js

This fixes #25.  I left `libpath` in to be backward compatible.  
I had trouble using the temporary fix proposed in #25 due to module caching.  I could not override the `java.classpath` for the module imported by `jdbc` by importing `java` myself.  This pull request fixed my issue.

add libs option to config for multiple jar support

---

lib/jdbc.js

At the moment all properties are retrieved as string, with this change it will try to match the retrieved sql column with its correct data type to the JavaScript object.

Retrieve columns with its correct data type when possible

---

lib/connection.js
lib/drivermanager.js
lib/jinst.js
lib/pool.js
lib/statement.js
test/test-multi.js

This pull request adds the statement.execute method, which allows both queries and updates.  This is useful if you don't know the query type in advance.  I also added tests based on the existing select and update tests.
I also fixed several small warnings/errors detected by jshint.

Add Statement.Execute Method

---

lib/resultset.js
test/test-multi.js

This pull request adds a toObject method which returns the type ids and column labels along with the rows.  This is useful when no results are returned.

Add toObject method that returns column labels and types

---

lib/resultset.js

Before the change this error occurred: `java.sql.SQLSyntaxErrorException: incompatible data type in conversion: from SQL type BIGINT to java.lang.Integer`.
According to this table `Long` should be used as the Java type for `BIGINT`: https://docs.oracle.com/cd/E19501-01/819-3659/gcmaz/

Changed type name for BIGINT

---

lib/resultset.js

Large result sets cause the async bit to blow its call stack, and regardless the entire resultset gets stored in memory this way. I wanted to get your thoughts on an iterator approach, so that users can consume rows and throw them away while they do so. This is a first draft solution and certainly open to ideas.

Return rows as an iterator

---

lib/callablestatement.js
lib/connection.js
lib/drivermanager.js
lib/pool.js
lib/statement.js
test/test-connection.js

Rewrote targeted methods to pull callback off the end of the arguments list, and dynamically handle the remainder.  In general, these methods follow the general pattern (as illustrated below for Connection.setClientInfo):
```javascript
// Get arguments as an array
var args = Array.prototype.slice.call(arguments);
// Pull the callback off the end of the arguments
callback = args.pop();
// Check arguments for validity, manipulate the args array appropriately,
// and return error if invalid
if (_.isObject(args[0]) && _.isUndefined(args[1]) && _.isUndefined(args[2])) {
// Do nothing
} else if (_.isNull(args[0]) && _.isString(args[1]) && _.isString(args[2])) {
// Remove first argument (props) from args array
args.shift();
} else {
return callback(new Error("INVALID ARGUMENTS"));
}
// Push a …
```

Solution to issue #80 - Un-promisifiable / callback argument consistency issue

---

lib/jinst.js
lib/pool.js
lib/statement.js

dded missing constants to Statement class, including:
CLOSE_CURRENT_RESULT
KEEP_CURRENT_RESULT
CLOSE_ALL_RESULTS
SUCCESS_NO_INFO
EXECUTE_FAILED
RETURN_GENERATED_KEYS
NO_GENERATED_KEYS
Refactored the work from the previous pull request (#83), which was closed shortly after I submitted it without merging; by getting rid of hard-coded values and replacing with dynamically pulled values that came from the original Java class, ie:
java.getStaticFieldValue('java.sql.Statement', 'CLOSE_CURRENT_RESULT`);
Also fixed issue of premature initialization of JDBC caused by calling getStaticFieldValue on jinst.java too soon. Solution implemented was to create an event emitter which emits an initialized event when a pool is initialized which triggers Statement initialization of values (via …

Solution to issue #82 - Missing static constants from Statement class, rev 3

---

lib/databasemetadata.js
package.json

Ported most (if not all) functionality from java.sql.DatabaseMetaData into databasemetadata.js - Not everything is completely fully-functional (one method returns the original object rather than a wrapped object), numerous methods could see more precise parameter checking (current checking is by data type but not values), and there is no test coverage

Feature 90 - Solution to issue #90

---

lib/statement.js

Wrapping result of Statement.getGeneratedKeys with ResultSet wrapper.

Feature 92 - Solution to Issue #92 - Statement.getGeneratedKeys should return a wrapped ResultSet

---

lib/databasemetadata.js
lib/resultset.js
lib/statement.js

Reworked ResultSet.getObjectIter() method.  Generally refactored it, but also added logic to return null for integers rather than zero, which is detected via getObjectSync().
Also includes style fixes (tabs to spaces) for two files (lib/databasemetadata.js, lib/statement.js).

Feature 94 - Solution to Issue #94

---

README.md
lib/pool.js
package.json
test/test-pool-maxidle.js

If you pass a **maxidle** property in the config for a new connection pool,
*pool.reserve()* will close stale connections, and will return a sufficiently fresh connection, or a new connection.
**maxidle** can be number representing the maximum number of milliseconds since a connection was last used, that
a connection is still considered alive (without making an extra call to the database to check that the connection is valid).
If **maxidle** is a falsy value or is absent from the config, this feature does not come into effect.
This feature is useful, when connections are automatically closed from the server side after a certain period of time,
and when it is not appropriate to use the connection keepalive feature.

Connections are closed after they have been idle for a certain period of time

---

lib/statement.js
test/test-statement-adjust.js

We need to set a limit to the number of rows returned by a query. Currently setFetchSize has been implemented but not setMaxRows. As explained in [https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html] fetch size specifies the number of rows to be retrieved from database when more rows needed. But what we need is to set a limit so that a specified max number of rows are retrieved at first. Thus I have added this setMaxRows function.

Added SetMaxRows function to statement and implemented related tests

---

lib/pool.js

Hi there,
At present the Pool.prototype.reserve function will return a new Error("No more pool connections available") even when the actual error from the JDBC driver is available.
This should be passed back to the calling application's callback function instead of this more generic error.
Cheers,
Matthew

Returning new JDBC Connection error to application

---

lib/callablestatement.js

This allows for calling stored procedures with output parameters.

Add wrapper for CallableStatement.registerOutParameter.

---

lib/resultset.js
lib/resultsetmetadata.js

Hi,
I've added exception handling in getColumnCount, and error checking in resultset.js -> toObjectIter.
Currently, if an the exception is raised during toObjectArray method - we cannot overcome it, and handle the returned error properly.

Fix unhandled exception in getColumnCount.

---

.travis.yml

1. Updated to Trusty
2. Added openjdk8 testing (which requires Trusty).
3. Reduced node version to latest release of each major version.

Updated travis testing configuration

---

lib/resultset.js

In some rare cases, when the query fails entirely, a run-time exception is thrown (and not handled):
'Reject row count exceeded.',
'\r',
'\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r',
'\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r',
'\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r',
'\tat java.lang.reflect.Method.invoke(Method.java:498)\r',
'',
'    at Object.next (node_modules\\jdbc\\lib\\resultset.js:103:38)',
'    at node_modules\\jdbc\\lib\\resultset.js:68:23',
'    at node_modules\\jdbc\\lib\\resultset.js:98:9',
'    at node_modules\\jdbc\\lib\\resultsetmetadata.js:12:14' ] }

Fix Java RuntimeException for failed queries.

---

.gitignore
lib/pool.js

The function call [properties.getPropertySync('user' | 'password')](https://docs.oracle.com/javase/7/docs/api/java/util/Properties.html#getProperty(java.lang.String)) does not return `undefined` in the new versions of java anymore, instead it now returns `null`.
To fix this bug i used the `_.isNil` function from [lodash](https://lodash.com/docs/4.17.10#isNil), so it can handle both cases.

fix(Pool): fix parameters initialization

---

lib/pool.js

Description:
-
Pool initialization fails when driver class name is passed for non-existing driver jars in classpath.
Steps to reproduce issue:
-
- Initialize pool with invalid drivername
- `java.newInstance` method call will return error and the callback will be called
```
java.lang.NoClassDefFoundError: org/postgresql/Driver
Caused by: java.lang.ClassNotFoundException: org.postgresql.Driver
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```
- `addConnection` will also fail and try to call callback again (https://github.com/CraZySacX/node-jdbc/blob/master/lib/pool.js#L153) 
``` …
```

fix for callback was already called - failing pool initialization code path 

---

lib/resultsetmetadata.js

Added `getColumnName` method to `ResultSetMetaData` class
Get the designated column's name.
**Parameters:**
column - the first column is 1, the second is 2, ...
**Returns:**
column name
https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSetMetaData.html#getColumnName-int-

add getColumnName method to ResultSetMetaData class

---

lib/resultset.js

Without the BigDecimal type identification (when encountered using UniVerse and UniData U2 jdbc drivers), values are incorrectly interpreted as strings.

BigDecimal fix

---

package.json
yarn.lock

The latest version of the Presto JDBC driver does not support getting data from the result set by boxed integer (`java.lang.Integer`), but only by the primitive `int` type. The `node-java` interop code converts all integers to boxed `java.lang.Integer` types. This creates a paradox whereby the codebase cannot be successfully utilized to connect to Presto.
JDBC drivers support data retrieval from result sets by passing in either the column index OR the column name / label. Data retrieval by column name also has more widespread support as it is more explicit. By updating the getters to use the `cmd.label` (column name) we are able to avoid the boxed integer issue and successfully utilize the presto JDBC driver.

Use column names instead of column indices in result set getters
